class ball{
    maxDist=10;
    s=10;
    constructor(_pos){
        this.pos=createVector(_pos.x,_pos.y);
        this.mov=createVector(0,0);
        this.dirDeg=random(0,360);
    }
    getNewDir(){this.dirDeg+=int(random(-60,60));}
    move(){
        
        if(int(random(1,100))==10){
            this.getNewDir();
        }
        this.mov.add(p5.Vector.fromAngle(radians(this.dirDeg), 1).mult(0.1));
        this.mov.mult(0.7);
        this.mov.limit(this.maxDist);
        this.pos.add(this.mov);
    }
    walls(){
        if(this.pos.x-this.s/2<0){
            this.mov.x+=5;
            this.dirDeg=90;
        }
        if(this.pos.x+this.s/2>width){
            this.mov.x-=5;
            this.dirDeg=270;
        }
        if(this.pos.y-this.s/2<0){
            this.mov.y+=5;
            this.dirDeg=180;
        }
        if(this.pos.y+this.s/2>height){
            this.mov.y-=5;
            this.dirDeg=0;
        }
    }
    draw(){
        fill(0);
        ellipse(this.pos.x,this.pos.y,this.s);
    }
}